apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dep
  labels:
    app: backend-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-dep
  template:
    metadata:
      labels:
        app: backend-dep
    spec:
      containers:
        - name: node-backend
          image: clarozzz/k8s-backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: DB_USER
              value: my-user
            - name: DB_PASS
              value: test
            - name: DB_NAME
              value: todos
            - name: DB_HOST
              value: postgres-svc
            - name: PORT
              value: "3001"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend-dep
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
