apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dep
  labels:
    app: frontend-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-dep
  template:
    metadata:
      labels:
        app: frontend-dep
    spec:
      containers:
        - name: vite-frontend
          image: clarozzz/k8s-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: VITE_API_URL
              value: http://backend-svc:3001
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend-dep
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
